language: bash
dist: focal

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
    packages:
      - docker-ce

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.5
    - THREADS=4
    - COMPOSER_GLOBAL_OPTIONS="--no-interaction --no-suggest -o"
    - PHP_IMAGE=wodby/drupal-php:7.3
    - DB_IMAGE=wodby/mariadb:10.4
  matrix:
    - CHECK_CS=true
    # Drupal 8.9.x highest.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^8.9 PHP_IMAGE=wodby/drupal-php:7.2
    # Drupal 9.x highest.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^9
    # Drupal 8.9.x lowest.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^8.9 PHP_IMAGE=wodby/drupal-php:7.2 DEPENDENCIES="--prefer-lowest"
    # Drupal 9.x lowest.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^9 DEPENDENCIES="--prefer-lowest"
    # Drupal 8.9.x Postgres.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^8.9 PHP_IMAGE=wodby/drupal-php:7.2 DB_DRIVER=pgsql DB_IMAGE=wodby/postgres:9.6
    # Drupal 8.9.x older MariaDB.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^8.9 PHP_IMAGE=wodby/drupal-php:7.2 DB_IMAGE=wodby/mariadb:10.3
    # Drupal 9.x Postgres.
    - RUN_PHPUNIT_TESTS=true DRUPAL_CORE=^9 DB_DRIVER=pgsql DB_IMAGE=wodby/postgres:10

matrix:
  fast_finish: true

before_install:
  - pip install travis-wait-improved
  - |
    sudo rm /usr/local/bin/docker-compose
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose && sudo mv docker-compose /usr/local/bin
  - |
    git clone https://github.com/Pronovix/docker-drupal-dev.git drupal-dev
    mkdir build;
    ln -s drupal-dev/docker-compose.yml
    ln -s drupal-dev/Dockerfile
    printf "COMPOSE_PROJECT_NAME=swagger_ui_formatter\n#You can find examples for available customization in the drupal-dev/examples/.env file.\n" > .env && source .env
  # Dummy permission fix for Travis CI because the default "travis" user's user id is not 1000 as you can see from the
  # the output of the "id" command:
  # uid=2000(travis) gid=2000(travis) groups=2000(travis),999(docker)
  # 1000 is usually the default user id of the first user in Linux systems. This is the id of the "wodby" user inside
  # the containers we use and if we do not fix this difference between the host and containers then we get file
  # permission issues while the build is running.
  - sudo chown -R 1000:travis . $HOME/.composer
  - mv .dev/.ci/travis.docker-compose.override.yml docker-compose.override.yml && sudo chmod g+x .dev/.ci/*.sh
  - docker-compose pull && docker-compose up -d --build && docker-compose ps

script:
  - set -e
  # Composer 1x can be really slow when it tries to figure out versions for a downgrade...
  # (travis_wait is only available in build. https://github.com/travis-ci/travis-ci/issues/9336#issuecomment-373149662)
  - travis-wait-improved --timeout 30m .dev/.ci/init-env.sh
  - .dev/.ci/check-cs.sh
  - .dev/.ci/run-phpunit-tests.sh
