name: Swagger UI Field Formatter
description: Provides a Swagger UI field formatter for File and Link fields.

dependencies:
  - drupal:file

type: module
core_version_requirement: ~8.9.1 || ^9
php: "7.2"
