name: Swagger UI Formatter QA

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
jobs:
  code_style:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Swagger UI Formatter
      uses: actions/checkout@v2

    - name: Setup DDEV
      uses: ddev/github-action-setup-ddev@v1
      with:
        autostart: false

    - name: Setup env
      run: |
        ddev config --php-version 8.1
        ddev dotenv set .ddev/.env --drupal-core "10.5.6"
        ddev dotenv set .ddev/.env --composer-no-security-blocking 1
        # Skip hooks and run commands directly to ensure when they fail
        # the step also fails immediately.
        ddev start --skip-hooks
        ddev poser
        ddev symlink-project

    - name: Run code style check
      run: ddev phpcs

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.1", "8.2", "8.3", "8.4"]
        db_version: ["mariadb:10.11"]
        # TODO Get version range from composer.json dynamically.
        # Hint: --prefer-lowest or COMPOSER_PREFER_LOWEST=1 does not work
        # with ddev poser because it runs `composer install` not
        # `composer update`.
        drupal_core_version: ["10.5.6", "^10.5.6", "11.2.10", "^11.2.10"]
        exclude:
          - php_version: "8.1"
            drupal_core_version: "11.2.10"
          - php_version: "8.2"
            drupal_core_version: "11.2.10"
          - php_version: "8.1"
            drupal_core_version: "^11.2.10"
          - php_version: "8.2"
            drupal_core_version: "^11.2.10"

    steps:
    - name: Checkout Swagger UI Formatter
      uses: actions/checkout@v2

    - name: Install DDEV
      uses: ddev/github-action-setup-ddev@v1
      with:
        autostart: false

    - name: Configure env
      run: |
        ddev config --php-version ${{ matrix.php_version }}
        ddev config --database ${{ matrix.db_version }}
        ddev dotenv set .ddev/.env --drupal-core "${{ matrix.drupal_core_version }}"
        # Mitigation for https://github.com/ddev/ddev-selenium-standalone-chrome/issues/76.
        if [[ "${{ matrix.drupal_core_version }}" == 10* ]] || [[ "${{ matrix.drupal_core_version }}" == ^10* ]]; then
            ddev dotenv set .ddev/.env --drupal-test-webdriver-w3c false
        fi
        ddev dotenv set .ddev/.env --composer-no-security-blocking 1
        # Skip hooks and run commands directly to ensure when they fail
        # the step also fails immediately.
        ddev start --skip-hooks
        ddev poser
        ddev symlink-project
        ddev yarn --cwd frontend
        ddev yarn --cwd frontend run build
        ddev describe

    - name: Run static code analyses
      run: ddev phpstan

    - name: Run tests
      run: ddev phpunit --debug
